version: '3.8'
services:
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    privileged: true
    volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker/:/var/lib/docker:ro
          - /dev/disk:/dev/disk/:ro
    ports:
        - '8080:8080'

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    user: root
    volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
          - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
        - '9090:9090'    

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    user: '0'
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=strongpassword
    ports:
        - "3000:3000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /var/lib/:/var/lib/
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
blackbox_exporter:
    image: prometheus/blackbox-exporter:latest
    container_name: blackbox_exporter
    volumes:
      - ./config:/config
