# my global config
global:
  scrape_interval:     5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    #metrics_path: /prometheus/metrics
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'blackbox'
    metrics_path: /probe
    tls_config:
          insecure_skip_verify: true
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://end-point:4567/data/health-check # Target to probe with http on port 8080.
        - http://end-point:4567/visual/health-check
        - http://end-point:4567/management/health-check
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox_exporter:9115']
